[package]
name = "lmutils"
version = "0.1.4"
edition = "2021"
description = "A set of utilities for working with linear regression models"
license = "MIT"
repository = "https://github.com/mrvillage/lmutils"

[dependencies]
csv = "1.3.0"
extendr-api = { version = "0.6.0", features = ["either"] }
faer = "0.18.2"
faer-ext = { version = "0.1.0", features = ["nalgebra"] }
flate2 = "1.0.30"
nalgebra = { version = "0.32.5", features = ["rayon"] }
rayon = "1.10.0"
rkyv = { version = "0.7.44", features = [
  "validation",
  "size_64",
  "std",
  "archive_le",
], default-features = false }
serde = { version = "1.0.202", features = ["derive"] }
serde_cbor = "0.11.2"
serde_json = "1.0.117"
thiserror = "1.0.61"
