[package]
name = "lmutils"
version = "0.2.1"
edition = "2021"
description = "A set of utilities for working with linear regression models"
license = "MIT"
repository = "https://github.com/mrvillage/lmutils"

[dependencies]
csv = "1.3.0"
extendr-api = { version = "0.6.0", features = ["either"] }
faer = "0.19"
flate2 = "1.0.30"
libc = "0.2.155"
memfile = "0.3.2"
rayon = "1.10.0"
rkyv = { version = "0.7.44", features = [
  "validation",
  "size_64",
  "std",
  "archive_le",
], default-features = false }
serde = { version = "1.0.202", features = ["derive"] }
serde_cbor = "0.11.2"
serde_json = "1.0.117"
statrs = "0.17.1"
thiserror = "1.0.61"
tracing = { version = "0.1.40", features = ["log"] }

[dev-dependencies]
rand = "0.8.5"
test-log = "0.2.16"
assert_float_eq = "1.1.3"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage_nightly)'] }
